CREATE TABLE gravadora(
    Codigo_Gravadora INT NOT NULL,
    Nome_Gravadora CHAR(60) NULL,
    Endereco CHAR(60) NULL,
    Telefone CHAR(20) NULL,
    Contato CHAR(20) NULL,
    URL CHAR(80) NULL
);

ALTER TABLE gravadora
    ADD CONSTRAINT XPKGRAVADORA PRIMARY KEY (Codigo_Gravadora);

CREATE TABLE CD (
    Codigo_CD INT NOT NULL,
    Codigo_Gravadora INT NULL,
    Nome_CD CHAR(60) NULL,
    Preco_Venda NUMERIC(14, 2) NULL,
    Data_Lancamento DATE NULL,
    CD_Indicado INT NULL
);

ALTER TABLE CD ADD CONSTRAINT XPKCD PRIMARY KEY (Codigo_CD);

ALTER TABLE CD ADD estilo CHAR(20);
ALTER TABLE CD ADD vendas NUMERIC(8, 2);

CREATE TABLE musica (
    Codigo_Musica INT NOT NULL,
    Nome_Musica CHAR(60) NULL,
    Duracao NUMERIC(6,2) NULL
);

ALTER TABLE musica
    ADD CONSTRAINT XPKMUSICA PRIMARY KEY (Codigo_Musica);

CREATE TABLE autor (
    Codigo_Autor INT NOT NULL,
    Nome_Autor CHAR(60) NULL
);

ALTER TABLE autor
    ADD CIBSTRAUBT XPKAUTOR PRIMARY KEY (Codigo_Autor);

CREATE TABLE MUSICA_AUTOR (
    Codigo_Musica INT NOT NULL,
    Codigo_Autor INT NOT NULL
);

ALTER TABLE MUSICA_AUTOR
    ADD CONSTRAINT XPKMUSICA_AUTOR PRIMARY KEY (Codigo_Musica, Codigo_Autor);

CREATE TABLE FAIXA (
    Codigo_Musica INT NOT NULL,
    Codigo_CD INT NOT NULL,
    Numero_Faixa INT NULL
);

ALTER TABLE FAIXA ADD CONSTRAINT XPKFAIXA PRIMARY KEY (Codigo_Musica, Codigo_CD);

CREATE TABLE CD_CATEGORIA (
    Codigo_Categoria INT NOT NULL,
    Menor_Preco NUMERIC(14,2) NOT NULL,
    Maior_Preco NUMERIC(14,2) NOT NULL
);

ALTER TABLE CD
       ADD  CONSTRAINT GRAVADORA_CD  FOREIGN KEY (Codigo_Gravadora) REFERENCES GRAVADORA;

ALTER TABLE CD
       ADD  CONSTRAINT CD_CD FOREIGN KEY (CD_Indicado) REFERENCES CD ;

ALTER TABLE MUSICA_AUTOR
       ADD  CONSTRAINT AUTOR_MUSICA_AUTOR FOREIGN KEY (Codigo_Autor) REFERENCES AUTOR ;


ALTER TABLE MUSICA_AUTOR
       ADD  CONSTRAINT MUSICA_MUSICA_AUTOR FOREIGN KEY (Codigo_Musica) REFERENCES MUSICA ;


ALTER TABLE FAIXA
       ADD  CONSTRAINT CD_FAIXA FOREIGN KEY (Codigo_CD) REFERENCES CD ;


ALTER TABLE FAIXA
       ADD  CONSTRAINT MUSICA_FAIXA FOREIGN KEY (Codigo_Musica) REFERENCES MUSICA ;