-- Inserir Dados em Vozes
INSERT INTO vozes(voz) VALUES('VOZ FLEXÍVEL');
INSERT INTO vozes(voz) VALUES('VOZ FINA');
INSERT INTO vozes(voz) VALUES('VOZ GROSSA');
INSERT INTO vozes(voz) VALUES('VOZ MASCULINA');
INSERT INTO vozes(voz) VALUES('VOZ MASCULA');
INSERT INTO vozes(voz) VALUES('VOZ FEMININA');
INSERT INTO vozes(voz) VALUES('VOZ CRIANÇA');